# Generated by Django 4.0.2 on 2022-03-02 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=20, unique=True, verbose_name='国籍')),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.CharField(max_length=50, unique=True, verbose_name='資格')),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10, unique=True, verbose_name='性別')),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('hourly_pay', models.IntegerField(blank=True, null=True)),
                ('residence', models.CharField(blank=True, max_length=100, null=True)),
                ('is_contact', models.BooleanField()),
                ('created_datetime', models.DateTimeField(auto_now_add=True)),
                ('updated_datetime', models.DateTimeField(auto_now=True)),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.citizenship')),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.requirement')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.sex')),
            ],
        ),
    ]
